name: "院内ルールの提案（かんたん）"
description: "ルール名と内容だけで申請できます。提出後は全員が閲覧できます。"
title: "[提案] <ルール名>"
labels:
  - proposal
body:
  - type: input
    id: rule_name
    attributes:
      label: ルール名
      description: 例) LINE返信、採血確認 など（ファイル名は自動生成）
      placeholder: 例) LINE返信
    validations:
      required: true
  - type: textarea
    id: rule_body
    attributes:
      label: 内容
      description: そのまま公開される本文を書いてください（箇条書き可）。
      placeholder: |
        - 受付は〜
        - 既読から10分以内に〜
    validations:
      required: true
