name: Validate Rules Changes

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate files and PR body
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const { owner, repo } = context.repo;
            const files = await github.paginate(github.pulls.listFiles, { owner, repo, pull_number: pr.number, per_page: 100 });
            const changed = files.filter(f => ['added','modified','renamed'].includes(f.status));
            const ruleFiles = changed.filter(f => f.filename.startsWith('rules/') && f.filename.endsWith('.md'));
            const invalid = [];
            for (const f of ruleFiles) {
              const base = f.filename.split('/').pop();
              if (!/^[0-9]{2}_.+\.md$/.test(base)) invalid.push(f.filename);
            }
            const body = pr.body || '';
            const hasDate = /施行日[:：]?\s*\d{4}-\d{2}-\d{2}/.test(body) || /\(施行日: \d{4}-\d{2}-\d{2}\)/.test(pr.title || '');
            const errors = [];
            if (invalid.length) errors.push(`ファイル名規則違反: ${invalid.join(', ')}`);
            if (!hasDate) errors.push('PR本文またはタイトルに施行日(YYYY-MM-DD)を含めてください');
            if (errors.length) core.setFailed(errors.join('\n'));

